# Generated by Django 5.2.6 on 2025-12-14 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('aircraft_type', models.CharField(blank=True, max_length=50)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('no_of_seats', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_type', models.CharField(default='Economy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('train_type', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('reach_time', models.TimeField()),
                ('no_of_seats', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coach_type', models.CharField(default='Sleeper', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], db_index=True, default='bus', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking_type',
            field=models.CharField(db_index=True, default='bus', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bus'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bus'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.flight'),
        ),
        migrations.AddField(
            model_name='payment',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.flight'),
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.flight')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.flightseat'),
        ),
        migrations.AddField(
            model_name='payment',
            name='flight_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.flightseat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.train'),
        ),
        migrations.AddField(
            model_name='payment',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.train'),
        ),
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('coach_number', models.CharField(default='S1', max_length=10)),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.train')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='train_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.trainseat'),
        ),
        migrations.AddField(
            model_name='payment',
            name='train_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.trainseat'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_type', 'status'], name='bookings_bo_booking_6c67f9_idx'),
        ),
        migrations.AddIndex(
            model_name='flightseat',
            index=models.Index(fields=['flight', 'is_booked'], name='bookings_fl_flight__9ab44c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainseat',
            index=models.Index(fields=['train', 'is_booked'], name='bookings_tr_train_i_972ee7_idx'),
        ),
    ]
